# Generated by Django 4.1 on 2023-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
